import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const app = read('../src/App.vue')
const router = read('../src/router/index.js')
const authDialog = read('../src/components/AuthDialog.vue')
const authApi = read('../src/api/auth.js')
const adminUsersView = read('../src/views/AdminUsersView.vue')
const adminFavoritesView = read('../src/views/AdminFavoritesView.vue')
const adminFeedbacksView = read('../src/views/AdminFeedbacksView.vue')
const adminCarsView = read('../src/views/AdminCarsView.vue')
const adminCarsApi = read('../src/api/adminCars.js')
const adminFavoritesApi = read('../src/api/adminFavorites.js')
const adminFeedbacksApi = read('../src/api/adminFeedbacks.js')

assert.doesNotMatch(authDialog, /测试账号|本地用户|本地管理员|el-radio-button|loginType/)
assert.match(authDialog, /管理员登录/)
assert.match(authDialog, /authStore\.login\(mode\.value === 'admin' \? 'ADMIN' : 'USER'/)
assert.match(authDialog, /authStore\.register/)
assert.match(authApi, /\/auth\/login/)

assert.match(app, /const brandTarget = computed\(\(\) => \(isAdmin\.value \? '\/admin\/cars' : '\/'\)\)/)
assert.match(app, /const showHomeMenu = computed\(\(\) => !authStore\.isAuthenticated \|\| !isAdmin\.value\)/)
assert.match(app, /item\.code !== 'home'/)
assert.match(app, /isAdmin\.value \? '管理员' : authStore\.displayName/)
assert.match(app, /const isAdminLayout = computed/)
assert.match(app, /adminMenuItems/)
assert.match(app, /admin-sidebar/)
assert.match(app, /adminVisibleMenus/)
assert.match(app, /\/admin\/cars/)
assert.match(app, /\/admin\/users/)
assert.match(app, /\/admin\/favorites/)
assert.match(app, /\/admin\/feedbacks/)
assert.match(app, /\/admin\/recommend-records/)
assert.match(app, /\/admin\/dashboard/)
assert.match(app, /\/admin\/health/)
assert.match(app, /\/algorithm-demo/)
assert.match(app, /SwitchButton/)
assert.doesNotMatch(app, /<el-menu-item[^>]*\/login|index="\/login"/)
assert.match(app, /<AuthDialog/)
assert.match(app, /account-pill/)

assert.match(router, /path: '\/admin\/login'/)
assert.match(router, /path: '\/admin\/favorites'/)
assert.match(router, /path: '\/admin\/feedbacks'/)
assert.match(router, /to\.name === 'home' && authStore\.isAuthenticated && authStore\.principalType === 'ADMIN'/)
assert.match(router, /return '\/admin\/cars'/)
assert.match(router, /buildAuthQuery\(to\.meta\.requiredRole === 'ADMIN' \? 'admin' : 'login', to\.fullPath\)/)
assert.doesNotMatch(router, /component: LoginView/)

assert.doesNotMatch(adminUsersView, />详情<|详情<\/el-button>|showDetail/)
assert.match(adminUsersView, /\/admin\/recommend-records/)
assert.match(adminUsersView, /\/admin\/favorites/)
assert.match(adminUsersView, /\/admin\/feedbacks/)
assert.match(adminUsersView, /SUCCESS.*完全匹配|完全匹配.*SUCCESS/)
assert.match(adminUsersView, /FALLBACK.*含补充推荐|含补充推荐.*FALLBACK/)
assert.match(adminUsersView, /EMPTY.*暂无结果|暂无结果.*EMPTY/)

assert.match(adminFavoritesView, /fetchAdminFavoriteCars/)
assert.match(adminFavoritesView, /fetchAdminFavoriteUsers/)
assert.doesNotMatch(adminFavoritesView, /delete|remove|取消收藏/)
assert.match(adminFavoritesApi, /\/admin\/favorites\/cars/)
assert.doesNotMatch(adminFavoritesApi, /delete|remove/)

assert.match(adminFeedbacksView, /fetchAdminFeedbacks/)
assert.match(adminFeedbacksView, /\/admin\/recommend-records/)
assert.doesNotMatch(adminFeedbacksView, /delete|remove|删除/)
assert.match(adminFeedbacksApi, /\/admin\/feedbacks/)
assert.doesNotMatch(adminFeedbacksApi, /delete|remove/)

assert.match(adminCarsView, /openImportDialog/)
assert.match(adminCarsView, /importAdminCarDataSource/)
assert.match(adminCarsView, /importResult\.successCount/)
assert.match(adminCarsView, /importResult\.issues/)
assert.match(adminCarsApi, /\/admin\/cars\/data-source\/import/)

console.log('admin experience checks passed')

function read(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), 'utf8')
}
