server:
  port: 8080

spring:
  application:
    name: cars-recommend-backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

debug: false

logging:
  level:
    root: INFO
    org.springframework: INFO
